### ISSUE TITLE
Method to reverse entropy

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#1]
Someday the energy is gonna run out, we need to think about how to get more. Is it possible?

Assigned a ASDFA task force to investigate the issue.

**Comment by msolters** [comment]
I have several ideas for unlimited energy
1. harness youtube comment arguments
2. harness stupid questions from yahoo answers 
3. harness energy previously dedicated towards safari bugs

**Comment by epheterson** [comment]
Saving or redirecting energy can never reverse it.

**Comment by msolters** [comment]
As my first step towards reducing randomness and chaos I will be closing this issue.
