### ISSUE TITLE
In full-view, rounded corners don't match

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#109]
top has larger radius than bottom

**Comment by epheterson** [comment]
![screen shot 2015-07-19 at 6 46 54 pm](https://cloud.githubusercontent.com/assets/151483/8768989/ac64ce92-2e46-11e5-8936-264cd3925943.png)

**Comment by msolters** [comment]
Yeah, this is also an easy fix.  Interestingly, it DOES look correct in Firefox, but not anywhere else.
