### ISSUE TITLE
Safari: Tiles not left-aligned

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#18]
![screen shot 2015-03-15 at 2 37 48 pm](https://cloud.githubusercontent.com/assets/151483/6658270/f23ce7d0-cb20-11e4-92bb-7dcf74e49b65.png)

**Comment by msolters** [comment]
Ugh. Safariiii

**Comment by msolters** [comment]
Ok, give it one more shot.  Make sure to shift-refresh.

**Comment by epheterson** [comment]
Working!
