### ISSUE TITLE
When Done / Cancel is necessary, show always on top

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#22]
Weird to go into the side menu to complete an action. Ex. the re-order category view, at first glance, looks like a bunch of categories w/out content.

**Comment by msolters** [comment]
I think this is more of an issue with the category sorting not being intuitive.

I like having all tools in the menu, and it is also a very logical decision for mobile since there is considerably less screen estate.

**Comment by msolters** [comment]
Anyway there's a lot of backend changes going on this weekend, so for the sake of simplicity I'm leaving all confirm/cancels in the menu.  I'll address perhaps moving them elsewhere at sufficiently large resolutions when I've ironed out the actual data structures and their CRUD behaviour.

**Comment by epheterson** [comment]
Sounds good, no real priority on this one

**Comment by msolters** [comment]
Sorting is the last feature waiting for this implementation now.
