### ISSUE TITLE
Different content for small / large view

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#25]
I think we had this implemented on the prior version, RIP.

**Comment by msolters** [comment]
What if in Edit mode, you can edit the "small" view in-place.
To edit the "large" view, you have to open it by clicking Edit button.  Still doesn't tell you what it will look like though, if the user wants HTML in their small view.

**Comment by msolters** [comment]
Two separate fields now, "Preview" and "Content".  One determines what the small tile says, the other is what populates the overlay when viewed in detail.  There is no automatic cross-over behaviour.  If you want preview material, you **must** specify it.

**Comment by epheterson** [comment]
Throwing this out there, how about a checkbox or something for if you want your small / large to be identical? Then you fill out one box and it copies over into the other (behind the scenes), instead of user requiring copy/paste every time?

**Comment by epheterson** [comment]
This would be a per-card setting, not universal
