### ISSUE TITLE
Exclude HTML in search

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#26]
Kinda on the fence on this one, though we'll be returning crap from hyperlinks and stuff. Ex. searching for "img" on mine right now returns most of my tiles (all with img tag).

**Comment by msolters** [comment]
There's only one way to do this.  It's gonna be a hack...we can pull the jQuery .text() value of the post-rendered DOM object just before we save it, and then put that in a separate field.  But that essentially means saving a double copy of any given Tile's data.  I see no other way around this than super complicated RegEx rules but that will frankly be slower.

**Comment by msolters** [comment]
Typical time vs space algorithm quandary.
