### ISSUE TITLE
Put shadow on top of content

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#27]
Doesn't make much sense as is, see screenshot where image appears to be atop shadow. 
![screen shot 2015-03-15 at 3 30 01 pm](https://cloud.githubusercontent.com/assets/151483/6658497/383e7ada-cb28-11e4-9a46-3f2a6659e6b8.png)

**Comment by msolters** [comment]
What browser?  Also it would help if u incl. browser name on most bugs, really helps narrow it down

**Comment by epheterson** [comment]
Think this is all browsers, no?

**Comment by msolters** [comment]
Shadows have been inverted for a while now!  (on development branch anyway)
