### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#29]
It'd be nice to be able to backup all my tiles to a lil file, create a fresh account, and import that file to have the exact same setup (ordering included). 

Especially important what with you erasing the database all the time, this level of confidence is required for us to start actually putting in content that we intend to persist, which makes for finding better real-world bugs.

**Comment by epheterson** [comment]
Or export / import, whatever you wanna call it

**Comment by msolters** [comment]
Yes, but, this will only be useful once I stop changing things every weekend.

**Comment by msolters** [comment]
Anyway I'm going to go ahead and start to build this, but backups will probably become incompatible as the backend is tweaked moving forward (especially with the future date picker structure)
