### ISSUE TITLE
File tiles top left 

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#3]

**Comment by msolters** [comment]
Change flex-column to center and justify: flex-start.  Then float left; this annihilates child width, which is a hack, but will force all tiles and category titles far left, as desired.  Then to reclaim scrolling, a parent class is wrapped around #tile-container with overflow-x: auto, and setting the float: left #tile-container to overflow: visible.  Very hacky but unfortunately side-ways first content layouts are not very robustly supported by modern browsers these days.
