### ISSUE TITLE
Fix date

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#4]
In more ways than one, replace date picker with something that allows months and years from yore to be easily chosen.

Also, present as:
2015
March 2015
March 15, 2015

Note the comma placement

**Comment by epheterson** [comment]
Also long dash to separate the dates

Short-dash
Long–dash

January 1, 1 – March 15, 2015

**Comment by msolters** [comment]
How do u type/encode that?

**Comment by epheterson** [comment]
&ndash;

http://line25.com/articles/10-html-entity-crimes-you-really-shouldnt-commit

**Comment by epheterson** [comment]
& ndash ;

**Comment by msolters** [comment]
Sweet reference dude, thanks.  it's been taken care of.

**Comment by msolters** [comment]
Reopened since the date picker still has to be fixed!

**Comment by epheterson** [comment]
Picker aside, the layout appears to be the same for me (except the dash is there, does look nice). The comma is what I mean, and it's missing the day.

**Comment by msolters** [comment]
Unfortunately you can't have it both ways -- it's either always with a day, or never with a day.  You decide.

**Comment by msolters** [comment]
Went with always!

**Comment by epheterson** [comment]
Nooo! Date is still incomplete

Must be able to choose just year, or year + month, or year + month + day. Any of those are reasonable. For example some projects lasted from 2010-2014 and the months don't really matter, this would be nice to be displayed. Or you know the months, but the days don't really matter. This is why Facebook-style dropdown make sense. First select the year via dropdown, then magically a month box appears. Select a month and magically a day box appears. This encourages entering of only the three options mentioned above, which should be easy do display. 

Most people will not know exact days of content in their tiles.

**Comment by msolters** [comment]
Well first of all, in order to make these tiles **searchable** or **sortable** by date, the dates must conform to iso8601 standards.

In short, if you just pick a **year**, what you **_really**_ mean is **Jan 1st of that year**.  A date MUST specify a month and a day, so if we hide one of those, we're implicitly assigning the remaining objects to the first element of their respective set.

**Comment by epheterson** [comment]
Not true dude, it's like... staged filtering. If exist year, sort by year, of that set if exist month, sort by that, if exist day, sort by that and one needn't depend on the next. This does require storing the three attributes separately, as they may not all come together (not storing as a single date value). 

It's the right way!

**Comment by msolters** [comment]
[this may be useful for sorting on vague fulltext](http://stackoverflow.com/questions/25498042/mongodb-full-text-search-and-multiple-words-sorted-by-relevance)

**Comment by msolters** [comment]
Ok I'm going to close this because we really only need the sorting aspect but that is separate from the idea of inputting date info in chunks, which now works.
