### ISSUE TITLE
Search Field Drops Out of Nav on Mobile

### ISSUE THREAD

**Issue by msolters** [msolters/Tiles#75]
We need a new way to search for mobile devices.  
-  Reduce the search area to just an icon
-  Maybe an overlay search box, triggered by the icon?

**Comment by msolters** [comment]
Hey dude give me some ideas for how search should work on mobile.  Try going to the site on your iphone to really get a sense of how cramped it is

**Comment by epheterson** [comment]
The solution is obvious : 
![img_0124](https://cloud.githubusercontent.com/assets/151483/8845963/1cf877e2-30d8-11e5-9cf6-eb8d053b083d.JPG)

**Comment by msolters** [comment]
So to help with this, I'm thinking of:
1.  Make user name smaller on mobile
2.  Search stacks underneath (small) name
3.  Move "change my name" feature to Settings > Profile
