### ISSUE TITLE
Don't strip out iframes

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#97]
New froala editor doesn't let me embed shit :

<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/131510800&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>

**Comment by epheterson** [comment]
Marking as bug because regression

**Comment by msolters** [comment]
What do you mean by embed?  Can you describe this issue a little bit more, im not quite on board

**Comment by epheterson** [comment]
Iframes are stripped out

**Comment by msolters** [comment]
No, I don't remove any iFrames.  But, if you are trying to enter HTML directly, make sure to enter HTML edit mode using the <> button in the top right:
![html mode](https://cloud.githubusercontent.com/assets/4452380/8768015/16964046-2e3f-11e5-8efe-11d2bda0a122.png)

**Comment by msolters** [comment]
If you just copypasta HTML in as rich text, then it will get saved as rich text, which is probably your issue:
![code as rich text](https://cloud.githubusercontent.com/assets/4452380/8768040/a0d1764a-2e3f-11e5-87e0-e518108bde49.png)

**Comment by msolters** [comment]
Please verify that you can embed iframes using the HTML-editor mode.  If it works (it should, it does for me) then you can go ahead and just close this.

**Comment by epheterson** [comment]
Weird, I swear I tried this one this morning and it didn't get saved, sounds good closing.

```
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/131510800&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
```
