### ISSUE TITLE
Bring back dates

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#98]
Not seeing a way to put in dates

**Comment by epheterson** [comment]
Marking as bug because regression

**Comment by msolters** [comment]
This is #4 man!

**Comment by msolters** [comment]
Also #81

**Comment by epheterson** [comment]
Kinda! When I filed those others there was a partially-functioning date feature

**Comment by msolters** [comment]
We need a complete redo of dates.  The last comment you have in #4 explains it:

> Not true dude, it's like... staged filtering. If exist year, sort by year, of that set if exist month, sort by that, if exist day, sort by that and one needn't depend on the next. This does require storing the three attributes separately, as they may not all come together (not storing as a single date value).
> 
> It's the right way!

That sounds like an accurate description of what we need, so we don't need duplicates on this
