### ISSUE TITLE
Full-height for fraoala editor

### ISSUE THREAD

**Issue by epheterson** [msolters/Tiles#99]
In Safari, at least, the editor only takes up about half the height of the window when it's full screen.

**Comment by epheterson** [comment]
Oh, also it has to grow. When it first starts off it's really short and you put a bunch of text in there but are stuck with the initial height to edit that text in.

**Comment by msolters** [comment]
In Chrome, the editor space expands in height with every Return Key strike.  Is this not the case in Safari?

**Comment by epheterson** [comment]
It's working now, not sure what was happening before. It seems to be growing correctly.
